name: .NET Selenium Tests

on:
  push:
    branches: [ main, testBranchSelenium ]
  pull_request:
    branches: [ main, testBranchSelenium ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.300  # Update to your specific .NET version (make sure it's supported on GitHub Actions)

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Check Chrome version
      run: google-chrome --version  # Check Chrome version to verify setup (optional)

    - name: Restore dependencies
      run: dotnet restore AutomationExerciseProj/AutomationExerciseProj.csproj

    - name: Build
      run: dotnet build AutomationExerciseProj/AutomationExerciseProj.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test AutomationExerciseProj/AutomationExerciseProj.csproj --no-build --verbosity normal
